from .design_prompts import (
    DESIGN_SYSTEM_PROMPT,
    IMAGE_ANALYSIS_PROMPT,
    CSS_GENERATION_PROMPT,
    REFINEMENT_PROMPT,
)

__all__ = [
    "DESIGN_SYSTEM_PROMPT",
    "IMAGE_ANALYSIS_PROMPT",
    "CSS_GENERATION_PROMPT",
    "REFINEMENT_PROMPT",
]
